# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: phelm.co.uk
email: website@phelm.co.uk
description: > # this means to ignore newlines until "baseurl:"
  the website of Phil Helm
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://phelm.co.uk" # the base hostname & protocol for your site
twitter_username: phelmphelm
github_username:  phelma

# Build settings
markdown: kramdown
